name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Check TypeScript
      run: npx tsc --noEmit
    
    - name: Lint
      run: |
        npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
        npx eslint . --ext .ts

  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Documentation
      run: |
        # Check if required documentation files exist
        for file in README.md CONFIGURATION.md API.md CONTRIBUTING.md PROMPTS.md; do
          if [ ! -f "$file" ]; then
            echo "Missing required documentation file: $file"
            exit 1
          fi
        done
        
        # Check for broken internal links
        for file in *.md; do
          grep -o "\[.*\](\.[^)]*)" "$file" | while read -r link; do
            file_path=$(echo "$link" | sed 's/.*(\(.*\))/\1/')
            if [ ! -f "${file_path#.}" ]; then
              echo "Broken link in $file: $link"
              exit 1
            fi
          done
        done

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit
      
    - name: Check for sensitive data
      run: |
        # Check for potential API keys
        if grep -r "POSTMAN_API_KEY.*=.*[A-Za-z0-9]" .; then
          echo "Found potential API key in code"
          exit 1
        fi